openapi: 3.0.3
info:
    title: Home expenses service
    description: Service for home expenses
    version: "1.0"
servers:
    - url: http://localhost:8000/
paths:
    /openapi.json:
        get:
            tags:
                - transactions
            summary: Download ./gen/http/openapi.json
            operationId: transactions#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /transactions:
        get:
            tags:
                - transactions
            summary: transactions transactions
            description: List all transactions.
            operationId: transactions#transactions
            responses:
                "200":
                    description: OK response.
                    headers:
                        marker:
                            description: Pagination marker
                            schema:
                                type: string
                                description: Pagination marker
                                example: Et et necessitatibus voluptatem.
                            example: Distinctio fugit eius odio aut et.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TransactionCollection'
                            example:
                                - account: Qui id repellat aut et.
                                  amount: 0.3992701
                                  category: Asperiores deserunt eveniet dolorem ea.
                                  cheque_no: 4408374357451353343
                                  date_posted: Consectetur animi sapiente accusamus.
                                  id: Soluta nostrum et voluptatem earum.
                                  notes: Provident ex impedit molestiae maiores unde.
                                  payee: Voluptatem et.
                                - account: Qui id repellat aut et.
                                  amount: 0.3992701
                                  category: Asperiores deserunt eveniet dolorem ea.
                                  cheque_no: 4408374357451353343
                                  date_posted: Consectetur animi sapiente accusamus.
                                  id: Soluta nostrum et voluptatem earum.
                                  notes: Provident ex impedit molestiae maiores unde.
                                  payee: Voluptatem et.
components:
    schemas:
        Transaction:
            type: object
            properties:
                account:
                    type: string
                    description: Account name.
                    example: Quae vel qui omnis a totam nesciunt.
                amount:
                    type: number
                    description: Dollar amount.
                    example: 0.4325624
                    format: float
                category:
                    type: string
                    description: Category.
                    example: Esse odio sed reprehenderit natus.
                cheque_no:
                    type: integer
                    description: Cheque number.
                    example: 7191856071321396198
                    format: int64
                date_posted:
                    type: string
                    description: Date posted.
                    example: Aut enim et et voluptatem et ipsa.
                id:
                    type: string
                    description: Identifier.
                    example: Animi ut distinctio soluta cum facilis.
                notes:
                    type: string
                    description: Notes.
                    example: Dolorem aut omnis inventore voluptate mollitia et.
                payee:
                    type: string
                    description: Payee name.
                    example: Nemo velit voluptatem consequatur.
            example:
                account: Aut tenetur in.
                amount: 0.06424373
                category: Optio in voluptatem aut.
                cheque_no: 5760254718931110017
                date_posted: Sint voluptatem.
                id: Qui similique corporis.
                notes: Dolor veniam accusantium cum sed.
                payee: Quo quia libero beatae.
            required:
                - id
                - date_posted
                - category
                - amount
        TransactionCollection:
            type: array
            items:
                $ref: '#/components/schemas/Transaction'
            example:
                - account: Qui id repellat aut et.
                  amount: 0.3992701
                  category: Asperiores deserunt eveniet dolorem ea.
                  cheque_no: 4408374357451353343
                  date_posted: Consectetur animi sapiente accusamus.
                  id: Soluta nostrum et voluptatem earum.
                  notes: Provident ex impedit molestiae maiores unde.
                  payee: Voluptatem et.
                - account: Qui id repellat aut et.
                  amount: 0.3992701
                  category: Asperiores deserunt eveniet dolorem ea.
                  cheque_no: 4408374357451353343
                  date_posted: Consectetur animi sapiente accusamus.
                  id: Soluta nostrum et voluptatem earum.
                  notes: Provident ex impedit molestiae maiores unde.
                  payee: Voluptatem et.
                - account: Qui id repellat aut et.
                  amount: 0.3992701
                  category: Asperiores deserunt eveniet dolorem ea.
                  cheque_no: 4408374357451353343
                  date_posted: Consectetur animi sapiente accusamus.
                  id: Soluta nostrum et voluptatem earum.
                  notes: Provident ex impedit molestiae maiores unde.
                  payee: Voluptatem et.
                - account: Qui id repellat aut et.
                  amount: 0.3992701
                  category: Asperiores deserunt eveniet dolorem ea.
                  cheque_no: 4408374357451353343
                  date_posted: Consectetur animi sapiente accusamus.
                  id: Soluta nostrum et voluptatem earum.
                  notes: Provident ex impedit molestiae maiores unde.
                  payee: Voluptatem et.
tags:
    - name: transactions
      description: The transactions service performs operations on transactions.
